-- CachyOS Hyprland Configuration

require("config.variables")
require("monitors")
require("config.autostart")
require("config.environment")
require("config.permissions")
require("config.decorations")
require("config.animations")
require("config.layout")
require("config.misc")
require("config.inputs")
require("config.binds")
require("config.rules")
require("config.workspaces")
