-- Generated by nwg-displays on 2026-09-04 at 17:52:54. Do not edit manually.

hl.monitor({
    output = "DP-2",
    mode = "3840x2160@240.0",
    position = "0x0",
    scale = 1.5,
    bitdepth = 10,
    cm = "srgb",
    vrr = 1
})
