-- Generated by nwg-displays on 2026-09-04 at 23:44:19. Do not edit manually.

hl.monitor({
    output = "DP-2",
    mode = "3840x2160@240.0",
    position = "0x0",
    scale = 1.5,
    bitdepth = 10,
    -- cm = "edid",
    cm = "srgb",
    -- cm = "hdredid",
    -- cm = "wide",
    -- cm = "auto"

    vrr = 0, -- fullscreen only
    -- vrr = 0, -- off
    -- vrr = 3, -- content type game
})

